:doctype: book
:stylesheet: ../prog.css

= Lesson 1: Python Basics

== Lesson Purpose:
This lesson is designed as a refresher for operating within a Python environment.  Students will be able expected to understand how to find modules from the Python standard library (PSL) and install them for use.  They will be introduced to working with non-PSL modules and how to install them from source.  The Python environment will be covered, along with working with virtual environments for projects within Python.
Students will discuss the differences between Python 2.7 and 3 programs, as well as the importance of knowing which version a script was designed to operate within.
Finally, students will be presented with Python best practices and working within an IDE.

== Learning Objectives:

----
1.         Python Basics
 1.1.     Intro to python modules
  1.1.1  PIP
  1.1.2. Installing from source
  1.1.3. PYTHONPATH
  1.1.4. Conda / Virtualenv
 1.2.     Python 2.7 vs 3
 1.3.     Working with IDEs
 1.4.     iPython
----

=== Required Resources:
-	Linux IDE VM

=== Pre-Reading:
-	Coming soon

== Exercises:

----
1.1	– PIP-boy, not just for survival situations
1.2	– Whose source is this anyways?
1.3	– Hide and Go Seek, Python Edition
1.4	– What’s Bigger than a Python?
1.5	– My Python is Better than yours
1.6	– All Hail the IDEs
1.7	– It’s only cool if it starts with an ‘i’
----

== References:

