:doctype: book
:stylesheet: ../prog.css

= Exercise 1_4: What’s Bigger than a Python?

=== Exercise Summary:
When building multiple Python projects on the same system, it is important to be able to control modules on a per project basis.  Python has easy to use virtualization techniques in virtualenv and conda.

== Learning Objectives:
----
1.         Python Basics
 1.1.     Intro to python modules
  1.1.1  PIP
  1.1.2. Installing from source
  1.1.3. PYTHONPATH
  1.1.4. Conda / Virtualenv
----

=== Narrative:
Create virtual environments for each of the following projects.  Install the necessary modules and run the executables.

== Instructions:
. The programmer for the Netmap program wants to implement the result in a web page rather than via console.  For this, he is experimenting with getting it to function within Django.  Use virtualenv to create a project named 'name' and install the requirements.txt file.  Sort through the project to find the key.
. Because the netmap application is smaller, the developer instead decided to use Tornado to get the results to render via a web browser.  Use conda to create a Python3 project named 'ex1_4_2' and install the required modules.

== Materials:
1)	ex1_4_1.zip
2)  ex1_4_2.zip

== References:
* “Presentations & Blog Posts”, Presentations & Blog Posts — Conda documentation. [Online]. Available: https://conda.io/docs/. [Accessed: 11-Mar-2017].
* K. Reitz, “Virtual Environments”, Virtual Environments — The Hitchhiker's Guide to Python, 2016. [Online]. Available: http://docs.python-guide.org/en/latest/dev/virtualenvs/. [Accessed: 11-Mar-2017].
* “Writing your first Django app, part 1”, Django. [Online]. Available: https://docs.djangoproject.com/en/1.10/intro/tutorial01/. [Accessed: 17-Mar-2017].
* https://www.tornadoweb.org/en/stable/guide/templates.html

== Instructor Notes:
. The ex1_4_1_requirements.txt file will install the Django module in the virtualenv.  Students then need to get Django functioning with the 'python manage.py runserver' command.  This will get the server up and functioning.  When students browse to the local port 8000, they will find the key to the exercise: 05804b18c8350d2cbbb8305f36eae304ca5afe84
. To build a conda Python 3 environment, use 'conda create -n ex1_4_2 python=3'.  After they get it running, they will notice an error on rendering for the key variable in ex1_4_2.  Because we are using Python 3 for this version of the program, the string needs to have an encoding defined.  Change the line to "key = sha1('ex1_4_2'.encode('utf-8')).hexdigest()" to get it working.  Key will be: f7f7f206c7b7261a8e987a79c39dde9805a5e260.

