:doctype: book
:stylesheet: ../prog.css

= Exercise 1_5: My Python is Better than yours

=== Exercise Summary:
Python has forked into two different communities, those who support Python2 and those who support Python3.  There are some distinct differences between the two versions, so it is important to know which version your script was written for.

== Learning Objectives:
----
1.         Python Basics
 1.2.     Python 2.7 vs 3
----

=== Narrative:
Follow the instructions to explore some of the differences between Python2 and Python3.

== Instructions:
. Conduct research into some of the differences between Python2 and 3.  Discuss.
. Try executing ex1_5_1.py, figure out how to make it work
. Extract ex1_5_2.zip, execute both of the scripts on the provided text file, discuss the differences.

== Materials:
. ex1_5_1.py
. ex1_5_2.zip

== References:
* S. Raschka, “The key differences between Python 2.7.x and Python 3.x with examples,” Sebastian Raschka's Website, 01-Jun-2014. [Online]. Available: http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html. [Accessed: 11-Mar-2017].

== Instructor Notes:

[start=2]
. ex1_5_1.py is using Python3 string statements in a Python2 and requires the futures import statement at the top to function correctly.
. ex1_5_2.zip contains a file parser in both Python2 and 3.  The text contains unicode which Python3 uses by default, and errors out when using Python2.
