:doctype: book
:stylesheet: ../prog.css

= Exercise 3_1: FOUR!

=== Exercise Summary:
In this exercise, students will be presented with regex challenges designed to introduce the basic concepts of regular expression.  This mini language has become a prevalent standard across many different programming languages for quickly parsing text based data for items of interest.  While the basics are simple to comprehend, the language itself can get extremely complicated.

== Learning Objectives:

----
3.         Script Writing
 3.1.     File Handling
 3.2.     User Input
 3.3.     Networking
 3.4.     REGEX
----

=== Narrative:
Many of the most popular security related tools available today are regex capable.  This mini-language is prevalent in everything from command line tools suck as grep, all the way up to high-priced pentesting analyzers.  The robustness of the capabilities of regular expression for pin-pointing precise data out of an immense data set makes it a must have skill for any IT Security professional.  In the following challenges, you are tasked with coming up with a regular expression that is capable to matching every item of the good column, while not matching on as many of the bad column as possible.  Scores for successful regular expressions are calculated as follows:
* 1 point per character of the regex (ie 'foo' == 3 points, '[abc]' == 5 points)
* 10 points per bad word matched

Try to achieve the lowest score you can get on each challenge.


== Instructions:
. D
. 

== Materials:
. 1_1 Baseline.pcap

== References:
* http://digitalcorpora.org/corpora/network-packet-dumps/

== Instructor Notes:
